/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_util_mmap_MMapBuffer */

#ifndef _Included_com_indeed_util_mmap_MMapBuffer
#define _Included_com_indeed_util_mmap_MMapBuffer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_indeed_util_mmap_MMapBuffer_PAGE_SIZE
#define com_indeed_util_mmap_MMapBuffer_PAGE_SIZE 4096L
#undef com_indeed_util_mmap_MMapBuffer_READ_ONLY
#define com_indeed_util_mmap_MMapBuffer_READ_ONLY 0L
#undef com_indeed_util_mmap_MMapBuffer_READ_WRITE
#define com_indeed_util_mmap_MMapBuffer_READ_WRITE 1L
#undef com_indeed_util_mmap_MMapBuffer_MAP_FAILED
#define com_indeed_util_mmap_MMapBuffer_MAP_FAILED -1LL
#undef com_indeed_util_mmap_MMapBuffer_MAP_SHARED
#define com_indeed_util_mmap_MMapBuffer_MAP_SHARED 1L
#undef com_indeed_util_mmap_MMapBuffer_MAP_PRIVATE
#define com_indeed_util_mmap_MMapBuffer_MAP_PRIVATE 2L
#undef com_indeed_util_mmap_MMapBuffer_MAP_ANONYMOUS
#define com_indeed_util_mmap_MMapBuffer_MAP_ANONYMOUS 4L
/*
 * Class:     com_indeed_util_mmap_MMapBuffer
 * Method:    mmap
 * Signature: (JIIIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_indeed_util_mmap_MMapBuffer_mmap
  (JNIEnv *, jclass, jlong, jint, jint, jint, jlong);

/*
 * Class:     com_indeed_util_mmap_MMapBuffer
 * Method:    munmap
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_util_mmap_MMapBuffer_munmap
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_indeed_util_mmap_MMapBuffer
 * Method:    mremap
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_indeed_util_mmap_MMapBuffer_mremap
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_indeed_util_mmap_MMapBuffer
 * Method:    msync
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_util_mmap_MMapBuffer_msync
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_indeed_util_mmap_MMapBuffer
 * Method:    madvise
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_util_mmap_MMapBuffer_madvise
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_indeed_util_mmap_MMapBuffer
 * Method:    errno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_indeed_util_mmap_MMapBuffer_errno
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
