/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_squall_mmap_NativeMemoryUtils */

#ifndef _Included_com_indeed_squall_mmap_NativeMemoryUtils
#define _Included_com_indeed_squall_mmap_NativeMemoryUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_indeed_squall_mmap_NativeMemoryUtils_UNSAFE_COPY_THRESHOLD
#define com_indeed_squall_mmap_NativeMemoryUtils_UNSAFE_COPY_THRESHOLD 1048576LL
#undef com_indeed_squall_mmap_NativeMemoryUtils_ENOMEM
#define com_indeed_squall_mmap_NativeMemoryUtils_ENOMEM 1L
#undef com_indeed_squall_mmap_NativeMemoryUtils_EPERM
#define com_indeed_squall_mmap_NativeMemoryUtils_EPERM 2L
#undef com_indeed_squall_mmap_NativeMemoryUtils_EAGAIN
#define com_indeed_squall_mmap_NativeMemoryUtils_EAGAIN 3L
#undef com_indeed_squall_mmap_NativeMemoryUtils_EFAULT
#define com_indeed_squall_mmap_NativeMemoryUtils_EFAULT 4L
#undef com_indeed_squall_mmap_NativeMemoryUtils_EINVAL
#define com_indeed_squall_mmap_NativeMemoryUtils_EINVAL 5L
/*
 * Class:     com_indeed_squall_mmap_NativeMemoryUtils
 * Method:    copyToDirectBuffer
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_indeed_squall_mmap_NativeMemoryUtils_copyToDirectBuffer
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     com_indeed_squall_mmap_NativeMemoryUtils
 * Method:    copyFromDirectBuffer
 * Signature: (Ljava/nio/ByteBuffer;IJI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_squall_mmap_NativeMemoryUtils_copyFromDirectBuffer
  (JNIEnv *, jclass, jobject, jint, jlong, jint);

/*
 * Class:     com_indeed_squall_mmap_NativeMemoryUtils
 * Method:    copyFromByteArray
 * Signature: ([BIIJ)V
 */
JNIEXPORT void JNICALL Java_com_indeed_squall_mmap_NativeMemoryUtils_copyFromByteArray
  (JNIEnv *, jclass, jbyteArray, jint, jint, jlong);

/*
 * Class:     com_indeed_squall_mmap_NativeMemoryUtils
 * Method:    copyToByteArray
 * Signature: (JI[BI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_squall_mmap_NativeMemoryUtils_copyToByteArray
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint);

/*
 * Class:     com_indeed_squall_mmap_NativeMemoryUtils
 * Method:    mlock0
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_squall_mmap_NativeMemoryUtils_mlock0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_indeed_squall_mmap_NativeMemoryUtils
 * Method:    munlock0
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_squall_mmap_NativeMemoryUtils_munlock0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_indeed_squall_mmap_NativeMemoryUtils
 * Method:    mincore
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_squall_mmap_NativeMemoryUtils_mincore
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
