/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_util_compress_zlib_ZlibCompressor_CompressionLevel */

#ifndef _Included_com_indeed_util_compress_zlib_ZlibCompressor_CompressionLevel
#define _Included_com_indeed_util_compress_zlib_ZlibCompressor_CompressionLevel
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
