/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_util_compress_zlib_ZlibCompressor_CompressionHeader */

#ifndef _Included_com_indeed_util_compress_zlib_ZlibCompressor_CompressionHeader
#define _Included_com_indeed_util_compress_zlib_ZlibCompressor_CompressionHeader
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
